apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-sandbox.fullname" . }}-env
data:
  CP_DB_URL: {{ .Values.env.CP_DB_URL | quote }}
  CP_BIND: {{ .Values.env.CP_BIND | quote }}
  CP_PORT: {{ .Values.env.CP_PORT | quote }}