apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent-sandbox.fullname" . }}-proxy
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: {{ include "agent-sandbox.name" . }}
      comp: proxy
  template:
    metadata:
      labels: 
        app: {{ include "agent-sandbox.name" . }}
        comp: proxy
    spec:
      containers:
        - name: proxy
          image: "{{ .Values.proxyImage.repository }}:{{ .Values.proxyImage.tag }}"
          imagePullPolicy: {{ .Values.proxyImage.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet: 
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet: 
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10