apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent-sandbox.fullname" . }}-cp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      app: {{ include "agent-sandbox.name" . }}
      comp: cp
  template:
    metadata:
      labels: 
        app: {{ include "agent-sandbox.name" . }}
        comp: cp
    spec:
      containers:
        - name: control-plane
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: 
                name: {{ include "agent-sandbox.fullname" . }}-env
            - secretRef: 
                name: {{ include "agent-sandbox.fullname" . }}-env
          livenessProbe:
            httpGet: 
              path: {{ .Values.livenessProbe.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet: 
              path: {{ .Values.readinessProbe.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}