apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-sandbox.fullname" . }}-cp
spec:
  type: {{ .Values.service.type }}
  selector: 
    app: {{ include "agent-sandbox.name" . }}
    comp: cp
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080