name: CI

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports: ["6379:6379"]
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: canopy
          POSTGRES_USER: canopy
          POSTGRES_DB: audit
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U canopy" 
          --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start server
        env:
          REDIS_URL: redis://localhost:6379/0
          DATABASE_URL: postgresql://canopy:canopy@localhost:5432/audit
          DEFAULT_QPS: "100"
          EGRESS_ALLOWLIST: "intranet.api,auth.internal.corp"
          TEAMS_SIGNING_SECRET: "ci-secret"
          BASE_URL: "http://localhost:8080"
          APPROVAL_SYNC_WAIT_MS: "15000"
          DEV_JWT_SECRET: "dev-secret"
          DEV_ISSUER: "canopyiq-dev"
          OIDC_AUDIENCE: "canopyiq-mcp"
          CANOPYIQ_POLICY_FILE: "./app/policies/samples.yaml"
        run: |
          # apply migration
          psql postgresql://canopy:canopy@localhost:5432/audit -f app/audit/migrate.sql
          # run server (background)
          nohup python -m uvicorn app.main:app --host 0.0.0.0 --port 8080 &

      - name: Wait for server
        run: |
          for i in {1..60}; do curl -sf http://localhost:8080/healthz && break; sleep 1; done

      - name: Run E2E
        env:
          PYTHONUNBUFFERED: "1"
        run: bash tests/e2e/ci_e2e.sh