{{- include "canopyiq.validateAutoscaling" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canopyiq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "canopyiq.labels" . | nindent 4 }}
  {{- with include "canopyiq.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "canopyiq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "canopyiq.podLabels" . | nindent 8 }}
      {{- with include "canopyiq.podAnnotations" . }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "canopyiq.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "canopyiq.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "canopyiq.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            # Environment variables from values.yaml
            {{- include "canopyiq.envVars" . | nindent 12 }}
            # Environment variables from configmap
            {{- if .Values.configMap.data }}
            {{- include "canopyiq.configMapEnvVars" . | nindent 12 }}
            {{- end }}
            # Environment variables from secrets
            {{- include "canopyiq.secretEnvVars" . | nindent 12 }}
          {{- if .Values.healthChecks.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthChecks.liveness.path }}
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.healthChecks.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.healthChecks.liveness.successThreshold }}
            failureThreshold: {{ .Values.healthChecks.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.healthChecks.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthChecks.readiness.path }}
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.healthChecks.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.healthChecks.readiness.successThreshold }}
            failureThreshold: {{ .Values.healthChecks.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # Temporary filesystem for read-only root filesystem
            - name: tmp
              mountPath: /tmp
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /app/data
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        # Temporary filesystem for read-only root filesystem
        - name: tmp
          emptyDir: {}
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "canopyiq.fullname" . }}-data
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}