{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "canopyiq.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "canopyiq.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with include "canopyiq.annotations" . }}
    {{- . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- include "canopyiq.storageClassName" . | nindent 2 }}
{{- end }}