# NOTE: This secret template is for demonstration purposes only.
# In production, secrets should be created externally and referenced by name,
# or managed by external secret management systems like:
# - External Secrets Operator
# - HashiCorp Vault
# - AWS Secrets Manager
# - Azure Key Vault
# - Google Secret Manager

# This template is only applied if secrets.createSecret is enabled
{{- if .Values.secrets.createSecret | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canopyiq.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "canopyiq.labels" . | nindent 4 }}
  {{- with include "canopyiq.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # Database connection URL - REPLACE WITH ACTUAL VALUE
  {{ .Values.secrets.keys.dbUrl }}: {{ "postgresql://username:password@hostname:5432/database" | b64enc }}
  
  # OIDC configuration - REPLACE WITH ACTUAL VALUES
  {{ .Values.secrets.keys.oidcIssuer }}: {{ "https://your-identity-provider.com" | b64enc }}
  {{ .Values.secrets.keys.oidcClientId }}: {{ "your-client-id" | b64enc }}
  {{ .Values.secrets.keys.oidcClientSecret }}: {{ "your-client-secret" | b64enc }}
  
  # Slack configuration - REPLACE WITH ACTUAL VALUES
  {{ .Values.secrets.keys.slackWebhookUrl }}: {{ "https://hooks.slack.com/services/YOUR/WEBHOOK/URL" | b64enc }}
  {{ .Values.secrets.keys.slackSigningSecret }}: {{ "your-slack-signing-secret" | b64enc }}
  
  # Session secret for JWT signing - REPLACE WITH ACTUAL VALUE
  {{ .Values.secrets.keys.sessionSecret }}: {{ randAlphaNum 32 | b64enc }}
{{- end }}

---
# Example of how to create the secret manually:
# kubectl create secret generic canopyiq-secret \
#   --from-literal=CP_DB_URL="postgresql://username:password@hostname:5432/database" \
#   --from-literal=OIDC_ISSUER="https://your-identity-provider.com" \
#   --from-literal=OIDC_CLIENT_ID="your-client-id" \
#   --from-literal=OIDC_CLIENT_SECRET="your-client-secret" \
#   --from-literal=SLACK_WEBHOOK_URL="https://hooks.slack.com/services/YOUR/WEBHOOK/URL" \
#   --from-literal=SLACK_SIGNING_SECRET="your-slack-signing-secret" \
#   --from-literal=SESSION_SECRET="$(openssl rand -base64 32)" \
#   --namespace=default